### ISSUE TITLE
umi3下 配置base路径后，菜单无法识别，面包屑无法显示

### ISSUE THREAD

**Issue by draco-china** [umijs/plugin-layout#11]

**Comment by Draco-china** [comment]
查看了下源代码，发现是以下两个文件中的 `base` 值固定为 `/`
`
plugin-layout/src/utils/getLayoutConfigFromRoute.ts
plugin-layout/src/utils/getMenuFromRoute.ts
`

**Comment by pandapandaQ** [comment]
请问最终如何解决了？

**Comment by pandapandaQ** [comment]
> _No description provided._

请问最终如何解决了？
