### ISSUE TITLE
开启了插件后其他路由例如登录怎么不应用布局插件？

### ISSUE THREAD

**Issue by robin-dongbin** [umijs/plugin-layout#4]
如题。
或者官方是否还会出一个plugin-login之类的插件？-

**Comment by robin-dongbin** [comment]
好像知道了，把`layout`配置里的两个选项都打开就行了，一时没转过来，建议在文档里加个tips之类的，比较方便使用的人

**Comment by HeskeyBaozi** [comment]
> 好像知道了，把`layout`配置里的两个选项都打开就行了，一时没转过来，建议在文档里加个tips之类的，比较方便使用的人

哪两个配置选项呀，大哥说清楚呀

**Comment by robin-dongbin** [comment]
> > 好像知道了，把`layout`配置里的两个选项都打开就行了，一时没转过来，建议在文档里加个tips之类的，比较方便使用的人
> 
> 哪两个配置选项呀，大哥说清楚呀

文档里的layout配置项不是就两个么？

**Comment by HeskeyBaozi** [comment]
不止两个呀？编译时配置和运行时配置就不止两个了，比如name, logo, locale。请问能说清楚吗？

**Comment by robin-dongbin** [comment]
我说的是配置项里有个layout配置项，没看到？

**Comment by HeskeyBaozi** [comment]
现在看到了。hideMenu、hideNav只是隐藏。整个路由还是在pro-layout的布局里。
插件编写里我觉得应该这里不应该写死强制套用在`/`路由下，应该作为配置项给用户配置
https://github.com/umijs/plugin-layout/blob/674dda5a2011d0bcb58361862048b07fdd3430f2/src/index.ts#L46-L52

**Comment by Hack-Jay** [comment]
` routes: [
    {
      path: '/user',
      component: '../layouts/UserLayout',
      layout: {
        hideMenu: true,
        // hideNav: true,
      },
      routes: [
        {
          name: 'login',
          path: '/user/login',
          component: '@/pages/user/login',
        },
      ],
    },
    { path: '/', component: '@/pages/index' },
    { component: '@/pages/404' },
  ],`

**Comment by Hack-Jay** [comment]
`
 routes: [
    {
      path: '/user',
      component: '../layouts/UserLayout',
      layout: {
        hideMenu: true,
        // hideNav: true,
      },
      routes: [
        {
          name: 'login',
          path: '/user/login',
          component: '@/pages/user/login',
        },
      ],
    },
    { path: '/', component: '@/pages/index' },
    { component: '@/pages/404' },
  ],
`

**Comment by Hack-Jay** [comment]
`
routes: [

    {
      path: '/user',
      component: '../layouts/UserLayout',
      layout: {
        hideMenu: true,
        // hideNav: true,
      },
      routes: [
        {
          name: 'login',
          path: '/user/login',
          component: '@/pages/user/login',
        },
      ],
    },
    { path: '/', component: '@/pages/index' },
    { component: '@/pages/404' },
  ],
`
